name: Monitoring

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check application health
        run: |
          curl -f https://taskday.com/actuator/health || exit 1
          
      - name: Check database connectivity
        run: |
          # Verificar conectividade com banco
          echo "Database health check"
          
      - name: Send notification on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
